# Generated by Django 4.2.1 on 2023-06-03 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proagua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleta',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='coleta',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='responsáveis'),
        ),
    ]
